ci:
  autoupdate_schedule: "quarterly"

default_language_version:
  python: "python3.13"

repos:
  - repo: "meta"
    hooks:
      - id: "check-hooks-apply"
      - id: "check-useless-excludes"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # frozen: v6.0.0
    hooks:
      - id: "check-added-large-files"
      - id: "check-merge-conflict"
      - id: "check-json"
      - id: "check-yaml"
      - id: "end-of-file-fixer"
      - id: "mixed-line-ending"
        args:
          - "--fix=lf"
      - id: "trailing-whitespace"

  - repo: "https://github.com/asottile/pyupgrade"
    rev: "75992aaa40730136014f34227e0135f63fc951b4"  # frozen: v3.21.2
    hooks:
      - id: "pyupgrade"
        name: "Enforce Python 3.13+ idioms"
        args:
          - "--py313-plus"

  - repo: "https://github.com/psf/black-pre-commit-mirror"
    rev: "96ae3e5802f3fe2d551e703e18f0a367d1a81ac2"  # frozen: 26.10.0
    hooks:
      - id: "black"

  - repo: "https://github.com/pycqa/isort"
    rev: "9f905615631c545f5aea2516508109350d1d2f7d"  # frozen: 9.0.2
    hooks:
      - id: "isort"

  - repo: "https://github.com/pycqa/flake8"
    rev: "cfbbfdeb2391c14a37e101e92a77f54f329e1726"  # frozen: 7.4.1
    hooks:
      - id: "flake8"
        additional_dependencies:
          - "flake8-toml-config==1.0.0"
          - "flake8-bugbear==25.11.29"

  - repo: "https://github.com/editorconfig-checker/editorconfig-checker"
    rev: "0adfdb012938ada0cf563a40f2fceaf9466290ca"  # frozen: v4.0.2
    hooks:
      - id: "editorconfig-checker"

  - repo: "https://github.com/python-jsonschema/check-jsonschema"
    rev: "4f85d46a92dc17713078e5de73f8a13190edf6fc"  # frozen: 0.38.2
    hooks:
      - id: "check-dependabot"
      - id: "check-github-workflows"
      - id: "check-metaschema"
        files: "src/.+-schema.json"

  - repo: "https://github.com/adhtruong/mirrors-typos"
    rev: "3eb3b00ab99fd9a875b2ca1e580651d33cef2ace"  # frozen: v1.50.3
    hooks:
      - id: "typos"

  - repo: "local"
    hooks:
      - id: "render-workflow-templates"
        name: "Render workflow templates"
        language: "python"
        entry: "python src/render-templates.py"
        always_run: true
        pass_filenames: false
        additional_dependencies:
          # The dependencies here are injected from a lock file
          # when `tox run -e update-requirements` is run.
          # DO NOT edit these dependencies manually.
          #
          # additional_dependencies source: requirements/templating/requirements.txt
          - 'jinja2==3.1.6 ; python_version == "3.13"'
          - 'markupsafe==3.0.3 ; python_version == "3.13"'

  - repo: "https://github.com/zizmorcore/zizmor-pre-commit"
    rev: "fa412071e4f5d44d44f9e365f4676f9df92456a2"  # frozen: v1.30.1
    hooks:
    - id: "zizmor"

  - repo: "https://github.com/rhysd/actionlint"
    rev: "914e7df21a07ef503a81201c76d2b11c789d3fca"  # frozen: v1.7.12
    hooks:
      - id: "actionlint"
        additional_dependencies:
          - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@4e7020840c303923eb1ab846fc446d77be892570"
