author: "Kurt McKee"
name: "Get the path to the reusable workflow's root directory"
description: |
  Get the path to the reusable workflow's root directory.

  GitHub Actions doesn't automatically checkout reusable workflows' repos,
  which means that if the reusable workflows rely on asset files to function
  (like shell scripts, Python code, JSON schemas, etc)
  then the assets must be embedded directly into the reusable workflow's YAML.

  However, GitHub Actions *does* automatically checkout actions' repos.
  Thus, this composite action exists solely to trigger automatic checkouts.

  Reusable workflows in this repo can use this action as their first step,
  then access all of their asset files via this action's sole output: `path`.

inputs: {}

outputs:
  path:
    description: |
      The path to this repository's checked-out files.
    value: "${{ steps.get-action-path.outputs.path }}"

runs:
  using: "composite"
  steps:
    - name: "Save the github.action_path value"
      id: "get-action-path"
      env:
        ACTION_PATH: "${{ github.action_path }}"
      shell: "bash"
      run: |
        echo "path=${ACTION_PATH}" >> "${GITHUB_OUTPUT}"
